trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: azureServiceConnection
  type: string
- name: subscriptionId
  type: string
- name: location
  type: string

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  resourceGroupName: 'module-02-rg'
  bicepFile: 'module-02/bicep/main.bicep'
  bicepParametersFile: 'bicep/main.bicepparam'

stages:
- stage: Validate
  displayName: 'Validate Module 02'
  jobs:
  - job: ValidateModule02
    displayName: 'Validate Module 02'
    steps:
    - checkout: self
      fetchDepth: 0
    - task: AzureCLI@2
      displayName: Lint main.bicep
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep install
          az bicep lint --file ${{ variables.bicepFile }} --diagnostics-format sarif > $(System.DefaultWorkingDirectory)/bicep.sarif
    # Install and run PSRule for Azure
    - task: ps-rule-install@2
      inputs:
        module: PSRule.Rules.Azure
        latest: true
        prerelease: false
    - task: ps-rule-assert@2
      displayName: Analyze Azure template files 
      inputs:
        inputType: inputPath
        inputPath: 'module-02/bicep/'
        modules: 'PSRule.Rules.Azure'

- stage: Deploy
  displayName: 'Deploy Module 02 Resources'
  dependsOn: Validate
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: DeployModule02
    displayName: 'Deploy Module 02'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
      # Azure Details
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ parameters.azureServiceConnection }}
        subscriptionId: ${{ parameters.subscriptionId }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourceGroupName }}
        location: ${{ parameters.location }}
      # Template
        templateLocation: 'Linked artifact'
        csmFile: ${{ variables.bicepFile }}
        csmParametersFile: ${{ variables.bicepParametersFile }}
      # Advanced
        deploymentMode: 'Incremental'