trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: azureServiceConnection
  type: string
- name: subscriptionId
  type: string
- name: location
  type: string

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  bicepFile: 'module-03/bicep/main.bicep'

stages:
- stage: DeployDev
  displayName: 'Deploy Module 03 Development Resources'
  jobs:
  - deployment: DeployModule03Dev
    displayName: Deploy Module 03 Development
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      resourceGroupName: 'module-03-dev-rg'
      deployEnvironmentName: 'module-03-dev'
    environment:
      name: ${{ variables.deployEnvironmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              fetchDepth: 0
            - task: AzureCLI@2
              displayName: 'Create Resource Group'
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  # Creating a resource group
                  echo "Creating resource group ${{ variables.resourceGroupName }} in location ${{ parameters.location }}"
                  az group create --name ${{ variables.resourceGroupName }} --location ${{ parameters.location }}
            - task: AzureCLI@2
              displayName: 'Run What-If Analysis'
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  # Run What-If deployment
                  echo "Running What-If deployment for ${{ variables.bicepFile }} in resource group ${{ variables.resourceGroupName }}"
                  az deployment group what-if --resource-group ${{ variables.resourceGroupName }} --template-file ${{ variables.bicepFile }}
            - task: AzureCLI@2
              displayName: 'Deploy Bicep'
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  # Deploying Bicep file
                  echo "Deploying Bicep file ${{ variables.bicepFile }} to resource group ${{ variables.resourceGroupName }}"
                  az deployment group create --resource-group ${{ variables.resourceGroupName }} --template-file ${{ variables.bicepFile }}
- stage: DeployDev
  displayName: 'Deploy Module 03 Production Resources'
  dependsOn: Validate
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - deployment: DeployModule03Prod
    displayName: Deploy Module 03 Production
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
      resourceGroupName: 'module-03-prod-rg'
      deployEnvironmentName: 'module-03-prod'
    environment:
      name: ${{ variables.deployEnvironmentName }}
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
              fetchDepth: 0
            - task: AzureCLI@2
              displayName: 'Create Resource Group'
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  # Creating a resource group
                  echo "Creating resource group ${{ variables.resourceGroupName }} in location ${{ parameters.location }}"
                  az group create --name ${{ variables.resourceGroupName }} --location ${{ parameters.location }}
            - task: AzureCLI@2
              displayName: 'Run What-If Analysis'
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  # Run What-If deployment
                  echo "Running What-If deployment for ${{ variables.bicepFile }} in resource group ${{ variables.resourceGroupName }}"
                  az deployment group what-if --resource-group ${{ variables.resourceGroupName }} --template-file ${{ variables.bicepFile }}
            - task: AzureCLI@2
              displayName: 'Deploy Bicep'
              inputs:
                azureSubscription: ${{ parameters.azureServiceConnection }}
                scriptType: bash
                scriptLocation: inlineScript
                inlineScript: |
                  # Deploying Bicep file
                  echo "Deploying Bicep file ${{ variables.bicepFile }} to resource group ${{ variables.resourceGroupName }}"
                  az deployment group create --resource-group ${{ variables.resourceGroupName }} --template-file ${{ variables.bicepFile }}