trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: azureServiceConnection
  type: string
- name: subscriptionId
  type: string
- name: location
  type: string

variables:
  resourceGroupName: 'module-01-rg'
  bicepFile: 'module-01/bicep/main.bicep'
  bicepParametersFile: 'module-01/bicep/main.bicepparam'

stages:
- stage: Validate
  displayName: 'Validate Module 01'
  jobs:
  - job: ValidateModule01
    displayName: 'Validate Module 01'
    steps:
    - checkout: self
      fetchDepth: 0
    - task: AzureCLI@2
      displayName: Lint main.bicep
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep install
          az bicep lint --file ${{ variables.bicepFile }} --diagnostics-format sarif > $(System.DefaultWorkingDirectory)/bicep.sarif
    # Run Gitleaks on Source Repository
    # - task: Gitleaks@3
    #   displayName: 'Run Gitleaks'
    #   inputs:
    #     scanlocation: '$(Build.SourcesDirectory)'
    #     configtype: 'predefined'
    #     predefinedconfigfile: 'GitleaksUdmCombo.toml'
    #     scanmode: 'directory'
    #     reportformat: 'sarif'

- stage: Deploy
  displayName: 'Deploy Module 01 Resources'
  dependsOn: Validate
  jobs:
  - job: DeployModule01
    displayName: 'Deploy Module 01'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Bicep file'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Creating a resource group
          az group create \
            --name ${{ variables.resourceGroupName }} \
            --location ${{ parameters.location }}
          # Deploying Bicep file
          az deployment group create \
            --name $(Build.BuildNumber) \
            --resource-group ${{ variables.resourceGroupName }} \
            --parameters ${{ variables.bicepParametersFile }}
