trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: azureServiceConnection
  type: string
- name: subscriptionId
  type: string
- name: location
  type: string

variables:
  resourceGroupName: 'module-01-rg'
  bicepFile: 'bicep/main.bicep'
  bicepParametersFile: 'bicep/main.bicepparam'

stages:
- stage: Validate
  displayName: 'Validate Module 01'
  jobs:
  - job: ValidateModule01
    displayName: 'Validate Module 01'
    steps:
    - checkout: self
      fetchDepth: 0
    - task: AzureCLI@2
      displayName: Lint main.bicep
      inputs:
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep install
          az bicep lint --file bicep/main.bicep --diagnostics-format sarif > $(System.DefaultWorkingDirectory)/bicep.sarif
    # Run Gitleaks on Source Repository
    - task: Gitleaks@3
      inputs:
        scanlocation: '$(Build.SourcesDirectory)'
        configtype: 'predefined'
        predefinedconfigfile: 'GitleaksUdmCombo.toml'
        scanmode: 'directory'
        reportformat: 'sarif'
    # Install and run PSRule for Azure
    - task: ps-rule-install@2
      inputs:
        module: PSRule.Rules.Azure
        latest: true
        prerelease: false
    - task: ps-rule-assert@2
      displayName: Analyze Azure template files 
      inputs:
        inputType: inputPath
        inputPath: 'bicep/'
        modules: 'PSRule.Rules.Azure'

- stage: Deploy
  displayName: 'Deploy Module 01 Resources'
  dependsOn: Validate
  jobs:
  - job: DeployModule01
    displayName: 'Deploy Module 01'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
      # Azure Details
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ${{ parameters.azureServiceConnection }}
        subscriptionId: ${{ parameters.subscriptionId }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourceGroupName }}
        location: ${{ parameters.location }}
      # Template
        templateLocation: 'Linked artifact'
        csmFile: ${{ variables.bicepFile }}
        csmParametersFile: ${{ variables.bicepParametersFile }}
      # Advanced
        deploymentMode: 'Incremental'