trigger: none

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: azureServiceConnection
  type: string
- name: subscriptionId
  type: string
- name: location
  type: string

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  resourceGroupName: 'module-01-rg'
  bicepFile: 'module-01/bicep/main.bicep'
  bicepParametersFile: 'module-01/bicep/main.bicepparam'

stages:
- stage: Validate
  displayName: 'Validate Module 01'
  jobs:
  - job: ValidateModule01
    displayName: 'Validate Module 01'
    steps:
    - checkout: self
    - task: AzureCLI@2
      displayName: Lint main.bicep
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az bicep install
          az bicep lint --file ${{ variables.bicepFile }} --diagnostics-format sarif > $(System.DefaultWorkingDirectory)/bicep.sarif
    - task: Gitleaks@3
      displayName: 'Run Gitleaks'
      inputs:
        scanlocation: '$(Build.SourcesDirectory)/module-01'
        configtype: 'predefined'
        predefinedconfigfile: '$(Build.SourcesDirectory)/.gitleaks.toml'
        scanmode: 'directory'
        reportformat: 'sarif'

- stage: Deploy
  displayName: 'Deploy Module 01 Resources'
  dependsOn: Validate
  condition: and(succeeded(), eq(variables.isMain, true))
  jobs:
  - job: DeployModule01
    displayName: 'Deploy Module 01'
    steps:
    - task: AzureCLI@2
      displayName: 'Create Resource Group'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Creating a resource group
          echo "Creating resource group ${{ variables.resourceGroupName }} in location ${{ parameters.location }}"
          az group create --name ${{ variables.resourceGroupName }} --location ${{ parameters.location }}
    - task: AzureCLI@2
      displayName: 'Run What-If Analysis'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Run What-If deployment
          echo "Running What-If deployment for ${{ variables.bicepFile }} in resource group ${{ variables.resourceGroupName }}"
          az deployment group what-if --resource-group ${{ variables.resourceGroupName }} --template-file ${{ variables.bicepFile }} --parameters ${{ variables.bicepParametersFile }}
    - task: AzureCLI@2
      displayName: 'Deploy Bicep'
      inputs:
        azureSubscription: ${{ parameters.azureServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          # Deploying Bicep file
          echo "Deploying Bicep file ${{ variables.bicepFile }} to resource group ${{ variables.resourceGroupName }}"
          az deployment group create --resource-group ${{ variables.resourceGroupName }} --template-file ${{ variables.bicepFile }} --parameters ${{ variables.bicepParametersFile }}

